-- ======================================================================
-- comment_test: one commented object for each of the eight CockroachDB
-- comment types (system.comments.type values 0 – 7)
-- ======================================================================


-- ── Type 0 · Database ──────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS comment_test;

COMMENT ON DATABASE comment_test
    IS '(database) Scratch database used to demonstrate all eight CockroachDB comment types.';

USE comment_test;


-- ── Type 4 · Schema ────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS inventory;

COMMENT ON SCHEMA inventory
    IS '(schema) Contains all tables, types, functions, and supporting objects for warehouse inventory management.';


-- ── Type 7 · User-Defined Type ─────────────────────────────────────────
CREATE TYPE IF NOT EXISTS inventory.condition AS ENUM (
    'new',
    'used',
    'refurbished',
    'damaged'
);

COMMENT ON TYPE inventory.condition
    IS '(type) Physical condition of a product unit when it is received into the warehouse.';


-- ── Type 1 · Table ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventory.products (
    product_id  INT8                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sku         STRING(50)          NOT NULL,
    name        STRING(200)         NOT NULL,
    unit_price  DECIMAL(12,2)       NOT NULL,
    condition   inventory.condition NOT NULL DEFAULT 'new',
    is_active   BOOL                NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ         NOT NULL DEFAULT now(),

    CONSTRAINT products_pkey       PRIMARY KEY (product_id),
    CONSTRAINT products_sku_uniq   UNIQUE      (sku),
    CONSTRAINT chk_positive_price  CHECK       (unit_price > 0)
);

COMMENT ON TABLE inventory.products
    IS '(table) Master catalogue of every product stocked in the warehouse; one row per distinct SKU.';


-- ── Type 2 · Column ────────────────────────────────────────────────────
COMMENT ON COLUMN inventory.products.sku
    IS '(column) Supplier-assigned stock-keeping unit code.  Must be globally unique across all suppliers.';


-- ── Type 5 · Constraint ────────────────────────────────────────────────
COMMENT ON CONSTRAINT chk_positive_price ON inventory.products
    IS '(constraint) Every stocked item must carry a positive list price; complimentary items are handled through a separate promotions workflow, not a zero price.';


-- ── Type 3 · Index ─────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_products_name
    ON inventory.products (name);

COMMENT ON INDEX inventory.products@idx_products_name
    IS '(index) Supports fast product-name searches and ORDER BY name queries across the full catalogue.';


-- ── Type 1 · View ──────────────────────────────────────────────────────
-- Views share comment type 1 (TableCommentType) with tables and sequences;
-- CockroachDB therefore uses COMMENT ON TABLE for views.
CREATE VIEW IF NOT EXISTS inventory.active_products AS
    SELECT  product_id,
            sku,
            name,
            unit_price,
            condition
    FROM    inventory.products
    WHERE   is_active = TRUE;

/* UNIMPLEMENTED
COMMENT ON VIEW inventory.active_products
    IS '(view) Live subset of inventory.products containing only items currently available for sale; discontinued products are automatically excluded.';
*/

-- ── Type 1 · Sequence ──────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS inventory.reorder_request_seq
    START WITH 1
    INCREMENT BY 1;

/* UNIMPLEMENTED
COMMENT ON SEQUENCE inventory.reorder_request_seq
    IS 'Monotonically increasing counter that assigns a unique reference number to each supplier reorder request.';
*/

-- ── Type 6 · Stored Function ───────────────────────────────────────────
-- Argument types are included in the COMMENT ON FUNCTION reference so that
-- the statement remains unambiguous if the function is later overloaded.
CREATE OR REPLACE FUNCTION inventory.discounted_price(list_price DECIMAL, discount_pct DECIMAL)
    RETURNS     DECIMAL
    LANGUAGE    SQL
    IMMUTABLE
AS $$
    SELECT ROUND(list_price * (1 - discount_pct / 100.0), 2)
$$;

/* UNIMPLEMENTED
COMMENT ON FUNCTION inventory.discounted_price(DECIMAL, DECIMAL)
    IS 'Returns list_price reduced by discount_pct percent (0–100), rounded to two decimal places.  Example: discounted_price(100.00, 15) → 85.00.';
*/

